name = "image-processing-worker"
main = "src/index.ts"
compatibility_date = "2023-05-18"
node_compat = true

[[r2_buckets]]
binding = "MY_BUCKET"
bucket_name = "jokerace-images"

[[queues.producers]]
queue = "image-processing-queue"
binding = "IMAGE_QUEUE"

[[queues.consumers]]
queue = "image-processing-queue"
max_batch_size = 10
max_batch_timeout = 5

[build]
command = "yarn install"
