name: PRs to test-main

on: 
  pull_request:
    branches: [test-main]
    types: [closed]
jobs:
  merge-test-main-back-to-dev:
    if: github.event.pull_request.merged == true
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set Git config
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
    - name: Merge test-main back to dev
      run: |
          git status
          git fetch
          git switch test-staging
          git pull
          git merge test-main
          git push